language: go

services:
  - docker
env:
  global:
    - IMAGE_NAME=jheidel/timelapse-queue
    - DOCKER_USERNAME=jheidel
    # DOCKER_PASSWORD provided by travis CI env variable

script:
  - docker build -t "$IMAGE_NAME" .

after_script:
  - docker images

jobs:
  include:
    - stage: test
      name: "Integration Test"
      script: echo TODO

    - stage: deploy
      name: "Deploy to Docker Hub"
      script: skip
      before_deploy:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
      deploy: docker push "${IMAGE_NAME}:latest"

